package com.almica.ramani

/**
 * 13feb2026 create style filter expression with json string and org.maplibre.android.style.expressions.Expression.Converter
 */
class StyleExpressionsJson {
    companion object {
        const val FILTER_COLOR_FILL_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"natural\"], \"coastline\"], [\"to-color\", \"#00A2E8\"], [\"==\", [\"get\", \"landuse\"], \"farmland\"], [\"to-color\", \"#fbecf7\"], [\"==\", [\"get\", \"landuse\"], \"farmyard\"], [\"to-color\", \"#f5dcba\"], [\"==\", [\"get\", \"landuse\"], \"grass\"], [\"to-color\", \"#cdebb0\"], [\"==\", [\"get\", \"natural\"], \"wood\"], [\"to-color\", \"#add196\"], [\"==\", [\"get\", \"natural\"], \"bare_rock\"], [\"to-color\", \"#e9e1d9\"], [\"==\", [\"get\", \"natural\"], \"scrub\"], [\"to-color\", \"#e8eac7\"], [\"==\", [\"get\", \"natural\"], \"beach\"], [\"to-color\", \"#fff1ba\"], [\"==\", [\"get\", \"natural\"], \"sand\"], [\"to-color\", \"#fff1ba\"], [\"==\", [\"get\", \"natural\"], \"wetland\"], [\"to-color\", \"#dbe8f5\"], [\"==\", [\"get\", \"natural\"], \"grassland\"], [\"to-color\", \"#cdebb0\"], [\"==\", [\"get\", \"landuse\"], \"cemetery\"], [\"to-color\", \"#aacbaf\"], [\"==\", [\"get\", \"landuse\"], \"recreation_ground\"], [\"to-color\", \"#dffce2\"], [\"==\", [\"get\", \"landuse\"], \"military\"], [\"to-color\", \"#f3e4de\"], [\"==\", [\"get\", \"landuse\"], \"landfill\"], [\"to-color\", \"#a7a87e\"], [\"==\", [\"get\", \"landuse\"], \"meadow\"], [\"to-color\", \"#a9be95\"], [\"==\", [\"get\", \"landuse\"], \"village_green\"], [\"to-color\", \"#cdebb0\"], [\"==\", [\"get\", \"landuse\"], \"residential\"], [\"to-color\", \"#F7BDA5\"], [\"==\", [\"get\", \"landuse\"], \"commercial\"], [\"to-color\", \"#c3b2b1\"], [\"==\", [\"get\", \"landuse\"], \"industrial\"], [\"to-color\", \"#beb3bc\"], [\"==\", [\"get\", \"landuse\"], \"allotments\"], [\"to-color\", \"#a6b79f\"], [\"==\", [\"get\", \"landuse\"], \"forest\"], [\"to-color\", \"#add19e\"], [\"==\", [\"get\", \"natural\"], \"water\"], [\"to-color\", \"#97c9d8\"], [\"==\", [\"get\", \"leisure\"], \"garden\"], [\"to-color\", \"#b5e3b5\"], [\"==\", [\"get\", \"leisure\"], \"water_park\"], [\"to-color\", \"#97c9d8\"], [\"==\", [\"get\", \"leisure\"], \"sports_centre\"], [\"to-color\", \"#c2e996\"], [\"==\", [\"get\", \"leisure\"], \"park\"], [\"to-color\", \"#a6c9a8\"], [\"==\", [\"get\", \"amenity\"], \"parking\"], [\"to-color\", \"#a09f9f\"], [\"==\", [\"get\", \"building\"], \"school\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"commercial\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"church\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"cathedral\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"hotel\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"office\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"retail\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"supermarket\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"warehouse\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"government\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"building\"], \"chapel\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"amenity\"], \"hospital\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"historic\"], \"castle\"], [\"to-color\", \"#d1af5e\"], [\"==\", [\"get\", \"aeroway\"], \"aerodrome\"], [\"to-color\", \"#bfbfcc\"], [\"to-color\", \"#a7a87e\"]]"
        const val FILTER_OPACITY_FILL_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"natural\"], \"coastline\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"farmland\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"farmyard\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"grass\"], 0.9, [\"==\", [\"get\", \"natural\"], \"wood\"], 0.9, [\"==\", [\"get\", \"natural\"], \"bare_rock\"], 0.9, [\"==\", [\"get\", \"natural\"], \"scrub\"], 0.9, [\"==\", [\"get\", \"natural\"], \"beach\"], 0.9, [\"==\", [\"get\", \"natural\"], \"sand\"], 0.9, [\"==\", [\"get\", \"natural\"], \"wetland\"], 0.9, [\"==\", [\"get\", \"natural\"], \"grassland\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"cemetery\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"recreation_ground\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"military\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"landfill\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"meadow\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"village_green\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"residential\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"commercial\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"industrial\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"allotments\"], 0.9, [\"==\", [\"get\", \"landuse\"], \"forest\"], 0.9, [\"==\", [\"get\", \"natural\"], \"water\"], 0.9, [\"==\", [\"get\", \"leisure\"], \"garden\"], 0.9, [\"==\", [\"get\", \"leisure\"], \"water_park\"], 0.9, [\"==\", [\"get\", \"leisure\"], \"sports_centre\"], 0.9, [\"==\", [\"get\", \"leisure\"], \"park\"], 0.9, [\"==\", [\"get\", \"amenity\"], \"parking\"], 0.9, [\"==\", [\"get\", \"building\"], \"school\"], 0.9, [\"==\", [\"get\", \"building\"], \"commercial\"], 0.9, [\"==\", [\"get\", \"building\"], \"church\"], 0.9, [\"==\", [\"get\", \"building\"], \"cathedral\"], 0.9, [\"==\", [\"get\", \"building\"], \"hotel\"], 0.9, [\"==\", [\"get\", \"building\"], \"office\"], 0.9, [\"==\", [\"get\", \"building\"], \"retail\"], 0.9, [\"==\", [\"get\", \"building\"], \"supermarket\"], 0.9, [\"==\", [\"get\", \"building\"], \"warehouse\"], 0.9, [\"==\", [\"get\", \"building\"], \"government\"], 0.9, [\"==\", [\"get\", \"building\"], \"chapel\"], 0.9, [\"==\", [\"get\", \"amenity\"], \"hospital\"], 0.9, [\"==\", [\"get\", \"historic\"], \"castle\"], 0.9, [\"==\", [\"get\", \"aeroway\"], \"aerodrome\"], 0.9, 0.0]"
        const val FILTER_COLOR_LINE_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"natural\"], \"coastline\"], [\"to-color\", \"#00A2E8\"], [\"==\", [\"get\", \"highway\"], \"primary\"], [\"to-color\", \"#FCCE21\"], [\"==\", [\"get\", \"highway\"], \"secondary\"], [\"to-color\", \"#E3E340\"], [\"==\", [\"get\", \"highway\"], \"tertiary\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"highway\"], \"residential\"], [\"to-color\", \"#FFF200\"], [\"==\", [\"get\", \"highway\"], \"footway\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"pedestrian\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"path\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"track\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"motorway_link\"], [\"to-color\", \"#FA914B\"], [\"==\", [\"get\", \"highway\"], \"trunk\"], [\"to-color\", \"#FA914B\"], [\"==\", [\"get\", \"highway\"], \"construction\"], [\"to-color\", \"#FA914B\"], [\"==\", [\"get\", \"highway\"], \"living_street\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"unclassified\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"service\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"highway\"], \"motorway\"], [\"to-color\", \"#FA914B\"], [\"==\", [\"get\", \"railway\"], \"rail\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"aeroway\"], \"aerodrome\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"leisure\"], \"sports_centre\"], [\"to-color\", \"#898989\"], [\"==\", [\"get\", \"building\"], \"school\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"commercial\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"industrial\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"church\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"cathedral\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"hotel\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"office\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"retail\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"supermarket\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"warehouse\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"government\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"chapel\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"yes\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"farm\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"farm_auxiliary\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"building\"], \"shed\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"amenity\"], \"hospital\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"amenity\"], \"restaurant\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"man_made\"], \"windmill\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"man_made\"], \"watermill\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"landuse\"], \"cemetery\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"natural\"], \"beach\"], [\"to-color\", \"#B97A57\"], [\"==\", [\"get\", \"waterway\"], \"river\"], [\"to-color\", \"#97c9d8\"], [\"==\", [\"get\", \"waterway\"], \"canal\"], [\"to-color\", \"#97c9d8\"], [\"==\", [\"get\", \"waterway\"], \"stream\"], [\"to-color\", \"#97c9d8\"], [\"==\", [\"get\", \"waterway\"], \"ditch\"], [\"to-color\", \"#97c9d8\"], [\"to-color\", \"#a7a87e\"]]"
        const val FILTER_WIDTH_LINE_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"natural\"], \"coastline\"], 6.0, [\"==\", [\"get\", \"highway\"], \"primary\"], 9.0, [\"==\", [\"get\", \"highway\"], \"secondary\"], 8.4, [\"==\", [\"get\", \"highway\"], \"tertiary\"], 7.8, [\"==\", [\"get\", \"highway\"], \"residential\"], 4.2, [\"==\", [\"get\", \"highway\"], \"motorway_link\"], 5.4, [\"==\", [\"get\", \"highway\"], \"trunk\"], 5.4, [\"==\", [\"get\", \"highway\"], \"rail\"], 4.2, [\"==\", [\"get\", \"highway\"], \"construction\"], 7.2, [\"==\", [\"get\", \"highway\"], \"living_street\"], 4.2, [\"==\", [\"get\", \"highway\"], \"unclassified\"], 3.0, [\"==\", [\"get\", \"highway\"], \"service\"], 3.0, [\"==\", [\"get\", \"highway\"], \"motorway\"], 9.0, [\"==\", [\"get\", \"highway\"], \"footway\"], 3.0, [\"==\", [\"get\", \"highway\"], \"pedestrian\"], 3.0, [\"==\", [\"get\", \"highway\"], \"path\"], 3.0, [\"==\", [\"get\", \"highway\"], \"track\"], 3.0, [\"==\", [\"get\", \"aeroway\"], \"aerodrome\"], 3.6, [\"==\", [\"get\", \"leisure\"], \"sports_centre\"], 4.8, [\"==\", [\"get\", \"building\"], \"school\"], 3.6, [\"==\", [\"get\", \"building\"], \"commercial\"], 3.6, [\"==\", [\"get\", \"building\"], \"industrial\"], 3.6, [\"==\", [\"get\", \"building\"], \"church\"], 3.6, [\"==\", [\"get\", \"building\"], \"cathedral\"], 3.6, [\"==\", [\"get\", \"building\"], \"hotel\"], 3.6, [\"==\", [\"get\", \"building\"], \"office\"], 3.6, [\"==\", [\"get\", \"building\"], \"retail\"], 3.6, [\"==\", [\"get\", \"building\"], \"supermarket\"], 3.6, [\"==\", [\"get\", \"building\"], \"warehouse\"], 3.6, [\"==\", [\"get\", \"building\"], \"government\"], 3.6, [\"==\", [\"get\", \"building\"], \"chapel\"], 3.6, [\"==\", [\"get\", \"building\"], \"yes\"], 3.6, [\"==\", [\"get\", \"building\"], \"farm\"], 3.6, [\"==\", [\"get\", \"building\"], \"farm_auxiliary\"], 3.6, [\"==\", [\"get\", \"building\"], \"shed\"], 3.6, [\"==\", [\"get\", \"amenity\"], \"hospital\"], 3.6, [\"==\", [\"get\", \"amenity\"], \"restaurant\"], 3.6, [\"==\", [\"get\", \"man_made\"], \"windmill\"], 3.6, [\"==\", [\"get\", \"man_made\"], \"watermill\"], 3.6, [\"==\", [\"get\", \"landuse\"], \"cemetery\"], 3.6, [\"==\", [\"get\", \"natural\"], \"beach\"], 12.0, [\"==\", [\"get\", \"waterway\"], \"river\"], 12.0, [\"==\", [\"get\", \"waterway\"], \"canal\"], 12.0, [\"==\", [\"get\", \"waterway\"], \"stream\"], 9.6, [\"==\", [\"get\", \"waterway\"], \"ditch\"], 6.0, 0.0]"
        const val FILTER_IMAGE_SYMBOL_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"amenity\"], \"place_of_worship\"], [\"image\", \"church\"], [\"==\", [\"get\", \"amenity\"], \"restaurant\"], [\"image\", \"restaurant\"], [\"==\", [\"get\", \"place\"], \"city\"], [\"image\", \"town\"], [\"==\", [\"get\", \"place\"], \"town\"], [\"image\", \"town\"], [\"==\", [\"get\", \"place\"], \"village\"], [\"image\", \"village\"], [\"==\", [\"get\", \"natural\"], \"peak\"], [\"image\", \"peak\"], [\"==\", [\"get\", \"shop\"], \"supermarket\"], [\"image\", \"supermarket\"], [\"==\", [\"get\", \"shop\"], \"bakery\"], [\"image\", \"bakery\"], [\"==\", [\"get\", \"amenity\"], \"fuel\"], [\"image\", \"fuel\"], [\"==\", [\"get\", \"amenity\"], \"pharmacy\"], [\"image\", \"pharmacy\"], [\"==\", [\"get\", \"building\"], \"school\"], [\"image\", \"school.outlined\"], [\"==\", [\"get\", \"building\"], \"hotel\"], [\"image\", \"hotel\"], [\"==\", [\"get\", \"amenity\"], \"hospital\"], [\"image\", \"hospital\"], [\"==\", [\"get\", \"leisure\"], \"sports_centre\"], [\"image\", \"sports_centre\"], [\"==\", [\"get\", \"leisure\"], \"water_park\"], [\"image\", \"water_park\"], [\"==\", [\"get\", \"highway\"], \"primary\"], [\"image\", \"living_street\"], [\"==\", [\"get\", \"highway\"], \"motorway\"], [\"image\", \"living_street\"], \"\"]"
        const val FILTER_NAME_SYMBOL_LAYER: String =
            "[\"case\", [\"==\", [\"get\", \"amenity\"], \"place_of_worship\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"amenity\"], \"restaurant\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"place\"], \"city\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"place\"], \"town\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"place\"], \"village\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"natural\"], \"peak\"], [\"to-string\", [\"get\", \"name\"]], [\"==\", [\"get\", \"highway\"], \"primary\"], [\"to-string\", [\"get\", \"ref\"]], [\"==\", [\"get\", \"highway\"], \"motorway\"], [\"to-string\", [\"get\", \"ref\"]], \"\"]"
    }
    /** replaces code for geojson fill layer
            val e = Expression.switchCase(Expression.eq(Expression.get(NATURAL), Expression.literal(COASTLINE)),
                Expression.toColor(Expression.literal(COLOR_COASTLINE)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(FARMLAND)),
                    Expression.toColor(Expression.literal(COLOR_FARMLAND)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(FARMYARD)),
                    Expression.toColor(Expression.literal(COLOR_FARMYARD)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(GRASS)),
                    Expression.toColor(Expression.literal(COLOR_GRASS)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(WOOD)),
                    Expression.toColor(Expression.literal(COLOR_WOOD)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(BARE_ROCK)),
                    Expression.toColor(Expression.literal(COLOR_BARE_ROCK)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(SCRUB)),
                    Expression.toColor(Expression.literal(COLOR_SCRUB)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(BEACH)),
                    Expression.toColor(Expression.literal(COLOR_BEACH)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(SAND)),
                    Expression.toColor(Expression.literal(COLOR_BEACH)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(WETLAND)),
                    Expression.toColor(Expression.literal(COLOR_WETLAND)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(GRASSLAND)),
                    Expression.toColor(Expression.literal(COLOR_GRASS)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(CEMETERY)),
                    Expression.toColor(Expression.literal(COLOR_CEMETERY)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(RECREATION_GROUND)),
                    Expression.toColor(Expression.literal(COLOR_RECREATION_GROUND)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(MILITARY)),
                    Expression.toColor(Expression.literal(COLOR_MILITARY)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(LANDFILL)),
                    Expression.toColor(Expression.literal(COLOR_LANDFILL)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(MEADOW)),
                    Expression.toColor(Expression.literal(COLOR_MEADOW)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(VILLAGE_GREEN)),
                    Expression.toColor(Expression.literal(COLOR_GRASS)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(RESIDENTIAL)),
                    Expression.toColor(Expression.literal(COLOR_RESIDENTIAL)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(COMMERCIAL)),
                    Expression.toColor(Expression.literal(COLOR_COMMERCIAL)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(INDUSTRIAL)),
                    Expression.toColor(Expression.literal(COLOR_INDUSTRIAL)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(ALLOTMENTS)),
                    Expression.toColor(Expression.literal(COLOR_ALLOTMENTS)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(FOREST)),
                    Expression.toColor(Expression.literal(COLOR_FOREST)),
                // macht alles grau schwarz
                //Expression.eq(Expression.get(NATURAL), Expression.literal(RAILWAY)),
                //    Expression.toColor(Expression.literal(Color.LTGRAY)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(WATER)),
                    Expression.toColor(Expression.literal(COLOR_WATER)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(GARDEN)),
                    Expression.toColor(Expression.literal(COLOR_GARDEN)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(WATER_PARK)),
                    Expression.toColor(Expression.literal(COLOR_WATERPARK)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(SPORTS_CENTRE)),
                    Expression.toColor(Expression.literal(COLOR_SPORTS_CENTRE)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(PARK)),
                    Expression.toColor(Expression.literal(COLOR_PARK)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(PARKING)),
                    Expression.toColor(Expression.literal(COLOR_PARKING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SCHOOL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(COMMERCIAL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHURCH)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CATHEDRAL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(HOTEL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(OFFICE)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(RETAIL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SUPERMARKET)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(WAREHOUSE)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(GOVERNMENT)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHAPEL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(HOSPITAL)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(HISTORIC), Expression.literal(CASTLE)),
                    Expression.toColor(Expression.literal(COLOR_BUILDING)),
                Expression.eq(Expression.get(AEROWAY), Expression.literal(AERODROME)),
                    Expression.toColor(Expression.literal(COLOR_AEROWAY)),
                Expression.toColor(Expression.literal(COLOR_LANDFILL)
            ))

    val o = Expression.switchCase(
    Expression.eq(Expression.get(NATURAL), Expression.literal(COASTLINE)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(FARMLAND)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(FARMYARD)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(GRASS)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(WOOD)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(BARE_ROCK)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(SCRUB)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(BEACH)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(SAND)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(WETLAND)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(NATURAL), Expression.literal(GRASSLAND)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(CEMETERY)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(RECREATION_GROUND)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(MILITARY)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(LANDFILL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(MEADOW)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(VILLAGE_GREEN)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(RESIDENTIAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(COMMERCIAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(INDUSTRIAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(ALLOTMENTS)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LANDUSE), Expression.literal(FOREST)),
    Expression.literal(0.9),
    // macht alles grau schwarz
    //Expression.eq(Expression.get(NATURAL), Expression.literal(RAILWAY)),
    //    Expression.toColor(Expression.literal(Color.LTGRAY)),
    Expression.eq(Expression.get(NATURAL), Expression.literal(WATER)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LEISURE), Expression.literal(GARDEN)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LEISURE), Expression.literal(WATER_PARK)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LEISURE), Expression.literal(SPORTS_CENTRE)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(LEISURE), Expression.literal(PARK)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(AMENITY), Expression.literal(PARKING)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(SCHOOL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(COMMERCIAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(CHURCH)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(CATHEDRAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(HOTEL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(OFFICE)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(RETAIL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(SUPERMARKET)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(WAREHOUSE)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(GOVERNMENT)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(BUILDING), Expression.literal(CHAPEL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(AMENITY), Expression.literal(HOSPITAL)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(HISTORIC), Expression.literal(CASTLE)),
    Expression.literal(0.9),
    Expression.eq(Expression.get(AEROWAY), Expression.literal(AERODROME)),
    Expression.literal(0.9),
    Expression.literal(0.0),
    )
*/
    /* replaces code for geojson line layer
                 val colorExpression = Expression.switchCase(
                Expression.eq(Expression.get(NATURAL), Expression.literal(COASTLINE)),
                    Expression.toColor(Expression.literal(COLOR_COASTLINE)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PRIMARY)),
                    Expression.toColor(Expression.literal(COLOR_HIGHWAY_PRIMARY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(SECONDARY)),
                    Expression.toColor(Expression.literal(COLOR_HIGHWAY_SECONDARY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TERTIARY)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_TERTIARY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(RESIDENTIAL)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_RESIDENTIAL)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(FOOTWAY)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PEDESTRIAN)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PATH)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TRACK)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),

                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY_LINK)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_MOTORWAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TRUNK)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_MOTORWAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(CONSTRUCTION)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_MOTORWAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(LIVING_STREET)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(UNCLASSIFIED)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(SERVICE)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_MOTORWAY)),
                Expression.eq(Expression.get(RAILWAY), Expression.literal(RAIL)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(AEROWAY), Expression.literal(AERODROME)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(SPORTS_CENTRE)),
                Expression.toColor(Expression.literal(COLOR_HIGHWAY_GRAY)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SCHOOL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(COMMERCIAL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(INDUSTRIAL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHURCH)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CATHEDRAL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(HOTEL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(OFFICE)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(RETAIL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SUPERMARKET)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(WAREHOUSE)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(GOVERNMENT)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHAPEL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(YES)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(FARM)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(FARM_AUXILIARY)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SHED)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(HOSPITAL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(RESTAURANT)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(MAN_MADE), Expression.literal(WINDMILL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(MAN_MADE), Expression.literal(WATERMILL)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(CEMETERY)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(BEACH)),
                Expression.toColor(Expression.literal(COLOR_BUILDING_BORDER)),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(RIVER)),
                Expression.toColor(Expression.literal(COLOR_WATER)),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(CANAL)),
                Expression.toColor(Expression.literal(COLOR_WATER)),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(STREAM)),
                Expression.toColor(Expression.literal(COLOR_WATER)),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(DITCH)),
                Expression.toColor(Expression.literal(COLOR_WATER)),

                Expression.toColor(Expression.literal((COLOR_LANDFILL)))
            )
            val widthOuterExpression = Expression.switchCase(
                Expression.eq(Expression.get(NATURAL), Expression.literal(COASTLINE)),
                Expression.literal(3 * 2.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PRIMARY)),
                    Expression.literal(3 * 3.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(SECONDARY)),
                Expression.literal(3 * 2.8),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TERTIARY)),
                Expression.literal(3 * 2.6),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(RESIDENTIAL)),
                Expression.literal(3 * 1.4),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY_LINK)),
                Expression.literal(3 * 1.8),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TRUNK)),
                Expression.literal(3 * 1.8),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(RAIL)),
                Expression.literal(3 * 1.4),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(CONSTRUCTION)),
                Expression.literal(3 * 2.4),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(LIVING_STREET)),
                Expression.literal(3 * 1.4),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(UNCLASSIFIED)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(SERVICE)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY)),
                Expression.literal(3 * 3.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(FOOTWAY)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PEDESTRIAN)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PATH)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(TRACK)),
                Expression.literal(3 * 1.0),
                Expression.eq(Expression.get(AEROWAY), Expression.literal(AERODROME)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(LEISURE), Expression.literal(SPORTS_CENTRE)),
                Expression.literal(3 * 1.6),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SCHOOL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(COMMERCIAL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(INDUSTRIAL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHURCH)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CATHEDRAL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(HOTEL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(OFFICE)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(RETAIL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SUPERMARKET)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(WAREHOUSE)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(GOVERNMENT)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(CHAPEL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(YES)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(FARM)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(FARM_AUXILIARY)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SHED)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(AMENITY), Expression.literal(HOSPITAL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(AMENITY), Expression.literal(RESTAURANT)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(MAN_MADE), Expression.literal(WINDMILL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(MAN_MADE), Expression.literal(WATERMILL)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(LANDUSE), Expression.literal(CEMETERY)),
                Expression.literal(3 * 1.2),
                Expression.eq(Expression.get(NATURAL), Expression.literal(BEACH)),
                Expression.literal(3 * 4.0),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(RIVER)),
                Expression.literal(3 * 4.0),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(CANAL)),
                Expression.literal(3 * 4.0),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(STREAM)),
                Expression.literal(3 * 3.2),
                Expression.eq(Expression.get(WATERWAY), Expression.literal(DITCH)),
                Expression.literal(3 * 2.0),

                Expression.literal(0.0)
            )
*/
/* replaces code for geojson symbol layer
            val imageExpression = Expression.switchCase(
                Expression.eq(Expression.get(AMENITY), Expression.literal(POW)),
                Expression.image(Expression.literal(CHURCH)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(RESTAURANT)),
                Expression.image(Expression.literal(RESTAURANT)),
                Expression.eq(Expression.get(PLACE), Expression.literal(CITY)),
                Expression.image(Expression.literal(TOWN)),
                Expression.eq(Expression.get(PLACE), Expression.literal(TOWN)),
                Expression.image(Expression.literal(TOWN)),
                Expression.eq(Expression.get(PLACE), Expression.literal(VILLAGE)),
                Expression.image(Expression.literal(VILLAGE)),
                Expression.eq(Expression.get(NATURAL), Expression.literal(PEAK)),
                Expression.image(Expression.literal(PEAK)),
                Expression.eq(Expression.get(SHOP), Expression.literal(SUPERMARKET)),
                Expression.image(Expression.literal(SUPERMARKET)),
                Expression.eq(Expression.get(SHOP), Expression.literal(BAKERY)),
                Expression.image(Expression.literal(BAKERY)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(FUEL)),
                Expression.image(Expression.literal(FUEL)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(PHARMACY)),
                Expression.image(Expression.literal(PHARMACY)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(SCHOOL)),
                Expression.image(Expression.literal(SCHOOL_OUTLINED)),
                Expression.eq(Expression.get(BUILDING), Expression.literal(HOTEL)),
                Expression.image(Expression.literal(HOTEL)),
                Expression.eq(Expression.get(AMENITY), Expression.literal(HOSPITAL)),
                Expression.image(Expression.literal(HOSPITAL)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(SPORTS_CENTRE)),
                Expression.image(Expression.literal(SPORTS_CENTRE)),
                Expression.eq(Expression.get(LEISURE), Expression.literal(WATER_PARK)),
                Expression.image(Expression.literal(WATER_PARK)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PRIMARY)),
                Expression.image(Expression.literal(LIVING_STREET)),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY)),
                Expression.image(Expression.literal(LIVING_STREET)),

                Expression.literal("")
            )
            val nameExpression = Expression.switchCase(
                Expression.eq(Expression.get(AMENITY), Expression.literal(POW)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(AMENITY), Expression.literal(RESTAURANT)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(PLACE), Expression.literal(CITY)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(PLACE), Expression.literal(TOWN)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(PLACE), Expression.literal(VILLAGE)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(NATURAL), Expression.literal(PEAK)),
                Expression.toString(Expression.get("name")),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(PRIMARY)),
                Expression.toString(Expression.get("ref")),
                Expression.eq(Expression.get(HIGHWAY), Expression.literal(MOTORWAY)),
                Expression.toString(Expression.get("ref")),

                Expression.literal("")
            )
 */
}