package com.almica.ramani.utils
// 01nov2025
data class MaplibreBgLayers(var list: List<String> =
    listOf("land",
        "landcover",
        "hillshade",
        "contour-line",
        "land-structure-polygon",
        "land-structure-line",
        "road-primary",
        "road-motorway-trunk",
        "admin-1-boundary-bg",
        "admin-0-boundary-bg",
        "admin-1-boundary",
        "admin-0-boundary",
        "admin-0-boundary-disputed")
)

data class MaplibreLayers(var list: Map<String, String> =
    mapOf(
        //Pair("land", "org.maplibre.android.style.layers.BackgroundLayer"),
        //Pair("landcover", "org.maplibre.android.style.layers.FillLayer"),
        Pair("national-park", "org.maplibre.android.style.layers.FillLayer"),
        Pair("national-park_tint-band", "org.maplibre.android.style.layers.LineLayer"),
        Pair("landuse", "org.maplibre.android.style.layers.FillLayer"),
        Pair("pitch-outline", "org.maplibre.android.style.layers.LineLayer"),
        Pair("waterway-shadow", "org.maplibre.android.style.layers.LineLayer"),
        Pair("water-shadow", "org.maplibre.android.style.layers.FillLayer"),
        Pair("waterway", "org.maplibre.android.style.layers.LineLayer"),
        Pair("water", "org.maplibre.android.style.layers.FillLayer"),
        Pair("water-depth", "org.maplibre.android.style.layers.FillLayer"),
        Pair("wetland", "org.maplibre.android.style.layers.FillLayer"),
        Pair("wetland-pattern", "org.maplibre.android.style.layers.FillLayer"),
        //Pair("hillshade", "org.maplibre.android.style.layers.FillLayer"),
        //Pair("contour-line", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("land-structure-polygon", "org.maplibre.android.style.layers.FillLayer"),
        //Pair("land-structure-line", "org.maplibre.android.style.layers.LineLayer"),
        Pair("aeroway-polygon", "org.maplibre.android.style.layers.FillLayer"),
        Pair("aeroway-line", "org.maplibre.android.style.layers.LineLayer"),
        Pair("building", "org.maplibre.android.style.layers.FillLayer"),
        Pair("building-underground", "org.maplibre.android.style.layers.FillLayer"),
        Pair("tunnel-minor-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-street-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-minor-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-secondary-tertiary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-primary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-major-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-motorway-trunk-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-path-trail", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-path-cycleway-piste", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-path", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-steps", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-pedestrian", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-construction", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-minor", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-minor-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-major-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-street", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-street-low", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-secondary-tertiary", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-primary", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-motorway-trunk", "org.maplibre.android.style.layers.LineLayer"),
        Pair("tunnel-oneway-arrow-blue", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("tunnel-oneway-arrow-white", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("cliff", "org.maplibre.android.style.layers.LineLayer"),
        Pair("ferry", "org.maplibre.android.style.layers.LineLayer"),
        Pair("ferry-auto", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-pedestrian-polygon-fill", "org.maplibre.android.style.layers.FillLayer"),
        Pair("road-pedestrian-polygon-pattern", "org.maplibre.android.style.layers.FillLayer"),
        Pair("road-path-bg", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-steps-bg", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-pedestrian-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-path-trail", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-path-cycleway-piste", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-path", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-steps", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-pedestrian", "org.maplibre.android.style.layers.LineLayer"),
        Pair("golf-hole-line", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-polygon", "org.maplibre.android.style.layers.FillLayer"),
        Pair("turning-feature-outline", "org.maplibre.android.style.layers.CircleLayer"),
        Pair("road-minor-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-street-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-minor-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-secondary-tertiary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-primary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-major-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-motorway-trunk-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("turning-feature", "org.maplibre.android.style.layers.CircleLayer"),
        Pair("road-construction", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-minor", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-minor-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-major-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-street", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-street-low", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-secondary-tertiary", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("road-primary", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("road-motorway-trunk", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-rail", "org.maplibre.android.style.layers.LineLayer"),
        Pair("road-rail-tracks", "org.maplibre.android.style.layers.LineLayer"),
        Pair("level-crossing", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-oneway-arrow-blue", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-oneway-arrow-white", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("crosswalks", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("gate-fence-hedge", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-path-bg", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-steps-bg", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-pedestrian-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-path-trail", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-path-cycleway-piste", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-path", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-steps", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-pedestrian", "org.maplibre.android.style.layers.LineLayer"),
        Pair("gate-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("bridge-minor-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-street-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-minor-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-secondary-tertiary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-primary-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-major-link-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-motorway-trunk-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-construction", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-minor", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-minor-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-major-link", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-street", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-street-low", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-secondary-tertiary", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-primary", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-motorway-trunk", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-major-link-2-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-motorway-trunk-2-case", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-major-link-2", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-motorway-trunk-2", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-oneway-arrow-blue", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("bridge-oneway-arrow-white", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("bridge-rail", "org.maplibre.android.style.layers.LineLayer"),
        Pair("bridge-rail-tracks", "org.maplibre.android.style.layers.LineLayer"),
        Pair("aerialway", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("admin-1-boundary-bg", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("admin-0-boundary-bg", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("admin-1-boundary", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("admin-0-boundary", "org.maplibre.android.style.layers.LineLayer"),
        //Pair("admin-0-boundary-disputed", "org.maplibre.android.style.layers.LineLayer"),
        Pair("contour-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("building-entrance", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("building-number-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("block-number-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-intersection", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-number-shield", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("road-exit-shield", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("path-pedestrian-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("golf-hole-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("ferry-aerialway-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("waterway-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("natural-line-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("natural-point-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("water-line-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("water-point-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("poi-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("transit-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("airport-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("settlement-subdivision-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("settlement-minor-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("settlement-major-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("state-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("country-label", "org.maplibre.android.style.layers.SymbolLayer"),
        Pair("continent-label", "org.maplibre.android.style.layers.SymbolLayer")
    )
)
